class AppTexts {
  static const String username = "Username";
  static const String password = "Password";
  static const String confirmPassword = "Confirm Password";
  static const String rememberMe = "Remember me ";
  static const String forgotThePassword = "Forgot the password?";
  static const String login = "Login";
  static const String orContinueWith = "or continue with";
  static const String facebook = "Facebook";
  static const String google = "Google";
  static const String dontHaveAnAccount = "don’t have an account ? ";
  static const String signUp = " Sign Up";
  static const String fillYourProfile = " Fill your Profile";
  static const String fullName = " Full Name";
  static const String emailAddress = "Email Address";
  static const String phoneNumber = "Phone Number";
  static const String next = "Next";
  static const String home = "Home";
  static const String topics = "Topics";
  static const String author = "Author";
  static const String bookMark = "Bookmark";
  static const String search = "Search";
  static const String entertainment = "entertainment";
  static const String general = "general";
  static const String health = "health";
  static const String science = "science";
  static const String sports = "sports";
  static const String technology = "technology";
}
